use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'FF_NetWork_Example' do
  pod 'FF_NetWork', :path => '../'

  target 'FF_NetWork_Tests' do
    inherit! :search_paths

    
  end
end
